src/project/application/urls.py
from django.urls import include, path

from . import api, views


urlpatterns = [
    path("", views.index, name="index"),
    path("accounts/login/", views.login, name="login"),
    path("accounts/logout/", views.logout, name="logout"),
    path("create-account/", views.create_account, name="create_account"),
    path("create-routine/", views.create_routine, name="create_routine"),
    path(
        "update-routine/<str:routine_id>/", views.update_routine, name="update_routine"
    ),
    path(
        "delete-routine/<str:routine_id>/", views.delete_routine, name="delete_routine"
    ),
    path("my-routines", views.my_routines, name="my_routines"),
    path("run-routine/<str:routine_id>/", views.run_routine, name="run_routine"),
    # path("api/routine", api.RoutineAPIView.as_view(), name="api_routine"),
    path("api/", include(api.api_urls)),
]

src/project/forge_fitness/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("application.urls"))]

src/project/application/models/exercise_routine.py
import json
from typing import Dict, Any, List, Self
from uuid import uuid4

from django.contrib.auth.models import User
from django.db import models, transaction
from django.utils import timezone

from application.enums.impact_options import ImpactOptions
from application.enums.routine_options import RoutineOptions
from application.forms.routine_form import RoutineForm
from .muscles import Muscle
from .equipment import Equipment


class ExerciseRoutine(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    routine_name = models.CharField(max_length=255)
    description = models.TextField()
    estimated_duration = models.IntegerField(
        help_text="Estimated time the routine takes in minutes."
    )
    impact = models.CharField(
        choices=ImpactOptions.choices,
        help_text="The difficulty of the exercise routine.",
    )
    routine_type = models.CharField(
        choices=RoutineOptions.choices, max_length=255, help_text="Type of routine."
    )
    is_public = models.BooleanField(
        default=False, help_text="Flag determining if this routine is public."
    )
    set_rest_time = models.IntegerField(
        default=45, help_text="Amount of rest between sets in seconds."
    )
    exercise_rest_time = models.IntegerField(
        default=600, help_text="Amount of rest between exercises in seconds."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def find_routine_exercises(self):
        return Exercise.objects.filter(routine=self).all()

    def __set_routine_exercises(self, routine_exercises: List[Dict[str, Any]]) -> None:
        """
        Deletes and then creates the exercises for the routine.
        :param routine_exercises: A list of exercises for the routine.
        :return: None
        """
        self.find_routine_exercises().delete()
        for i, exercise in enumerate(routine_exercises):
            Exercise.objects.create(
                routine=self,
                exercise=exercise.get("exercise"),
                reps=exercise.get("reps"),
                sets=exercise.get("sets"),
                duration=exercise.get("duration"),
                order=i,
            )

    def find_routine_equipment(self):
        return RoutineEquipment.objects.filter(routine=self).all()

    def __set_routine_equipment(self, routine_equipment: List[Equipment]) -> None:
        """
        Deletes and then creates the equipment for the routine.
        :param routine_equipment: A list of required equipments for the routine.
        :return: None
        """
        self.find_routine_equipment().delete()
        for equipment in routine_equipment:
            RoutineEquipment.objects.create(routine=self, equipment=equipment)

    def find_routine_target_muscles(self):
        return RoutineTargetMuscle.objects.filter(routine=self).all()

    def __set_routine_target_muscles(self, target_muscles: List[Muscle]) -> None:
        """
        Deletes and then creates the target muscles for the routine.
        :param target_muscles: A list of target muscles for the routine.
        :return: None.
        """
        self.find_routine_target_muscles().delete()
        for muscle in target_muscles:
            RoutineTargetMuscle.objects.create(routine=self, muscle=muscle)

    def find_routine_tags(self):
        return RoutineTag.objects.filter(routine=self).all()

    def __set_routine_tags(self, routine_tags: List[str]) -> None:
        """
        Deletes and then creates the tags for the routine.
        :param routine_tags:
        :return:
        """
        self.find_routine_tags().delete()
        for tag in routine_tags:
            RoutineTag.objects.create(routine=self, tag=tag)

    @classmethod
    def create_routine(cls, form: RoutineForm, user: User) -> Self:
        """
        Creates a new routine for the given form.
        :param form: The form containing the routine.
        :param user: The user who created the routine.
        :return: The new routine.
        """
        with transaction.atomic():
            routine = ExerciseRoutine.objects.create(
                creator=user,
                routine_name=form.cleaned_data["routine_name"],
                description=form.cleaned_data["description"],
                estimated_duration=form.cleaned_data["estimated_duration"],
                impact=form.cleaned_data["impact"],
                routine_type=form.cleaned_data["routine_type"],
                is_public=form.cleaned_data["is_public"],
                set_rest_time=form.cleaned_data["set_rest_time"],
                exercise_rest_time=form.cleaned_data["exercise_rest_time"],
            )
            routine.__set_routine_exercises(form.cleaned_data["routine"])
            routine.__set_routine_equipment(form.cleaned_data["equipment"])
            routine.__set_routine_target_muscles(form.cleaned_data["target_muscles"])
            routine.__set_routine_tags(form.cleaned_data["tags"])
            return routine

    def update_routine(self, form: RoutineForm) -> None:
        """
        Updates the routine with the new values.
        :param form: The form containing the updated routine.
        :return: None.
        """
        with transaction.atomic():
            self.routine_name = form.cleaned_data["routine_name"]
            self.description = form.cleaned_data["description"]
            self.estimated_duration = form.cleaned_data["estimated_duration"]
            self.set_rest_time = form.cleaned_data["set_rest_time"]
            self.exercise_rest_time = form.cleaned_data["exercise_rest_time"]
            self.impact = form.cleaned_data["impact"]
            self.routine_type = form.cleaned_data["routine_type"]
            self.updated_at = timezone.now()
            self.__set_routine_exercises(form.cleaned_data["routine"])
            self.__set_routine_equipment(form.cleaned_data["equipment"])
            self.__set_routine_target_muscles(form.cleaned_data["target_muscles"])
            self.__set_routine_tags(form.cleaned_data["tags"])
            self.save()

    def to_dict(self):
        exercises = [exercise.to_dict() for exercise in self.find_routine_exercises()]

        equipment_ids = [
            equipment.get_equipment_fk_id()
            for equipment in self.find_routine_equipment()
        ]

        target_muscle_ids = [
            muscle.get_muscle_fk_id() for muscle in self.find_routine_target_muscles()
        ]

        tags = ", ".join(tag.tag for tag in self.find_routine_tags())

        return {
            "routine_name": self.routine_name,
            "description": self.description,
            "estimated_duration": self.estimated_duration,
            "impact": self.impact,
            "tags": tags,
            "target_muscles": target_muscle_ids,
            "routine_type": self.routine_type,
            "equipment": equipment_ids,
            "is_public": self.is_public,
            "set_rest_time": self.set_rest_time,
            "exercise_rest_time": self.exercise_rest_time,
            "routine": json.dumps(exercises),
        }


class Exercise(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    routine = models.ForeignKey(ExerciseRoutine, on_delete=models.CASCADE)
    exercise = models.CharField(max_length=255, help_text="The name of the exercise.")
    reps = models.IntegerField(default=10, help_text="Number of reps (Strength only).")
    sets = models.IntegerField(default=3, help_text="Number of sets (Strength only).")
    duration = models.IntegerField(
        default=30, help_text="Duration of the exercise in seconds (Cardio only)."
    )
    order = models.IntegerField(
        help_text="The order of the exercise within the routine."
    )

    def to_dict(self):
        return {
            "exercise": self.exercise,
            "reps": self.reps,
            "sets": self.sets,
            "duration": self.duration,
        }


class RoutineTag(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    routine = models.ForeignKey(ExerciseRoutine, on_delete=models.CASCADE)
    tag = models.CharField(max_length=255)


class RoutineTargetMuscle(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    routine = models.ForeignKey(ExerciseRoutine, on_delete=models.CASCADE)
    muscle = models.ForeignKey(Muscle, on_delete=models.CASCADE)

    def get_muscle_fk_id(self) -> int:
        return self.muscle.id


class RoutineEquipment(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    routine = models.ForeignKey(ExerciseRoutine, on_delete=models.CASCADE)
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)

    def get_equipment_fk_id(self) -> int:
        return self.equipment.id

src/project/application/forms/routine_form.py
from django import forms
from django.core.validators import MinValueValidator

from application.enums.impact_options import ImpactOptions
from application.enums.routine_options import RoutineOptions
from application.models import Equipment, Muscle


class RoutineForm(forms.Form):
    routine_name = forms.CharField(
        required=True, error_messages={"required": "Routine name is required."}
    )
    description = forms.CharField(
        required=True,
        max_length=250,
        error_messages={"required": "Description is required."},
        widget=forms.Textarea,
    )
    estimated_duration = forms.IntegerField(
        required=True,
        error_messages={
            "required": "Estimated time is required.",
            "min_value": "Estimated time must at least 5 minutes.",
        },
        validators=[MinValueValidator(4)],
    )
    set_rest_time = forms.IntegerField(
        initial=45,
        help_text="Rest time between sets in seconds.",
        error_messages={
            "required": "Rest time between sets is required.",
            "min_value": "Set rest time must at least 5 seconds.",
        },
        validators=[MinValueValidator(4)],
    )
    exercise_rest_time = forms.IntegerField(
        initial=60,
        help_text="Rest time between exercise in seconds.",
        error_messages={
            "required": "Rest time between exercises is required.",
            "min_value": "Rest time must at least 5 seconds.",
        },
        validators=[MinValueValidator(4)],
    )
    impact = forms.ChoiceField(
        initial=ImpactOptions.MEDIUM,
        required=True,
        choices=ImpactOptions.choices,
        error_messages={"required": "Impact level is required."},
    )
    tags = forms.CharField(required=False, help_text="Comma separated tags")
    target_muscles = forms.ModelMultipleChoiceField(
        queryset=Muscle.objects.all(),
        widget=forms.SelectMultiple,
        required=True,
        error_messages={
            "required": "At least one target muscle is required.",
            "invalid": "The muscle group selected is not valid.",
        },
    )
    routine_type = forms.ChoiceField(
        initial=RoutineOptions.CARDIO,
        required=True,
        choices=RoutineOptions.choices,
        error_messages={"required": "Routine type is required."},
    )
    equipment = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Equipment.objects.all(),
        widget=forms.SelectMultiple,
        error_messages={"invalid": "The equipment selected is not valid."},
    )
    is_public = forms.BooleanField(
        initial=False, required=False, widget=forms.CheckboxInput
    )
    routine = forms.JSONField(
        initial=[],
        required=True,
        error_messages={"required": "Your routine is empty. Build your routine."},
    )

    def clean_tags(self):
        tags = self.cleaned_data["tags"]
        if tags:
            return [tag.strip().replace(" ", "_") for tag in tags.split(",")]

src/project/application/views/create_account.py
import logging

from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from application.forms.account_creation import AccountCreationForm
from application.models.user_preferences import UserPreferences
from application.utils.form_messages import add_error_messages
from application.utils.login_user import login_user


def create_account(request):
    form = AccountCreationForm()
    if request.method == "POST":
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.create_user(
                    username=form.cleaned_data["username"],
                    email=form.cleaned_data["email"],
                    password=form.cleaned_data["password"],
                )
                user_preferences = UserPreferences(
                    user=user,
                    gender=form.cleaned_data["gender"],
                    units=form.cleaned_data["preferred_units"],
                )
                user.save()
                user_preferences.save()
                messages.success(request, "Account created successfully!")

                if login_user(
                    request,
                    form.cleaned_data["username"],
                    form.cleaned_data["password"],
                ):
                    return redirect("/")
                else:
                    messages.error(request, "An error occurred while logging in!")
                    return redirect("/")
            except Exception as e:
                logging.error(e)
                messages.error(
                    request, "An error occurred while creating your account."
                )
        else:
            add_error_messages(form, request)
    return render(request, "application/create_account.html", {"form": form})

src/project/application/views/create_routine.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.handlers.wsgi import WSGIRequest
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.urls.base import reverse

from application.forms.routine_form import RoutineForm
from application.utils.form_messages import add_error_messages
from application.models.exercise_routine import ExerciseRoutine


@login_required
def create_routine(request: WSGIRequest) -> HttpResponse:
    """
    Creates a new routine in the database.
    :param request: Information about the request.
    :return: Either a blank form (GET calls), or creates a new routine in the database (POST calls).
    """
    form = RoutineForm()
    if request.method == "POST":
        form = RoutineForm(request.POST)
        if form.is_valid():
            try:
                routine = ExerciseRoutine.create_routine(form, request.user)
                messages.success(request, "Routine created successfully!")
                return redirect(
                    reverse("update_routine", kwargs={"routine_id": routine.uuid})
                )
            except Exception as error:
                logging.error(error)
                messages.error(request, "An error occurred while creating the routine.")
        else:
            add_error_messages(form, request)
    return render(request, "application/create_routine.html", {"form": form})

src/project/application/views/index.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    return render(request, "application/base.html")

src/project/application/views/login.py
from django.contrib import messages
from django.shortcuts import render, redirect

from application.utils.login_user import login_user


def login(request, next_route: str = "/"):
    if request.method == "POST":
        post_data = request.POST
        username = post_data.get("username")
        password = post_data.get("password")
        if username is None:
            messages.error(request, "Username is required.")
        elif password is None:
            messages.error(request, "Password is required.")
        else:
            if login_user(request, username, password):
                return redirect(next_route)
    return render(request, "application/login.html")

src/project/application/views/logout.py
from django.contrib import messages
from django.contrib.auth import logout as d_logout
from django.shortcuts import redirect


def logout(request):
    d_logout(request)
    messages.success(request, "You have been logged out")
    return redirect("/")

src/project/application/templates/application/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Forge Fitness</title>
        <script src="{% static 'application/js/jquery.min.js' %}"></script>
        <link href="{% static 'application/font-awesome/css/all.css' %}" rel="stylesheet" />

        <link rel="stylesheet" href="{% static 'application/css/base.css' %}">
        <script src="{% static 'application/js/base.js' %}"></script>

        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        {% block extra_head %}

        {% endblock %}

    </head>
    <body>
        <div id="alert-messages">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} alert-message"{% endif %}>
                    <span>{{ message }}</span>
                    <i id="" class="fa-solid fa-x close-message-btn"></i>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div id="body">
            {% if user.is_authenticated %}
                {% include 'application/menu_bar.html' %}
            {% endif %}
            <div id="content">
                <div style="margin-bottom: 25px;">
                    {% include 'application/theme_switcher.html' %}
                </div>
                {% block content %}
                <div>Place your content here</div>
                {% endblock %}
            </div>
        </div>
    </body>
</html>

src/project/application/templates/application/create_account.html
{% extends "application/base.html" %}
{% load static %}

{% block content %}
    <div class="center-content">
        <div id="create-account" class="create-account-form-container">
            <div class="centered-image">
                <img src="{% static 'application/images/ForgeFitness.webp' %}" alt="Forge Fitness Logo">
            </div>
            <form action="." method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="input-group">
                    {{ field.label_tag }}
                    {{ field }}
                </div>
                {% endfor %}
                <div class="input-group">
                    <input type="submit" value="Create Account">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

src/project/application/templates/application/create_routine.html
{% extends "application/base.html" %}
{% load static %}

{% block content %}

<script src="{% static 'application/js/create_routine.js' %}"></script>
<link href="{% static 'application/css/create_routine.css' %}" rel="stylesheet" />

<div class="center-content">
    <div class="create-routine-form-container">
        <div class="row">
            <div class="col-50 col-md-100 form-container">
                <form action="." method="post">
                    {% csrf_token %}
                    <h3>Routine Info</h3>
                    <div class="input-group">
                        <label for="routine-name">Routine Name</label>
                        <input type="text" id="routine-name" name="routine_name" placeholder="" required value="{{ form.routine_name.value|default:'' }}">
                    </div>
                    <div class="row">
                        <div class="col-50 col-md-100 vertically-center">
                            <div class="checkbox-input-group">
                                <label for="id_is_public">Make routine public: </label>
                                {{ form.is_public }}
                            </div>
                        </div>
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="id_routine_type">Routine Type</label>
                                {{ form.routine_type }}
                            </div>
                        </div>
                    </div>

                    <div class="row for-strength-routine">
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="id_set_rest">Rest Between Sets (seconds)</label>
                                {{ form.set_rest_time }}
                            </div>
                        </div>
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="id_exercise_rest">Rest Between Exercise (seconds)</label>
                                {{ form.exercise_rest_time }}
                            </div>
                        </div>
                    </div>

                    <div class="input-group">
                        <label for="id_description">Description</label>
                        {{ form.description }}
                    </div>
                    <div class="row">
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="estimated-time">Estimated Time (minutes)</label>
                                <input type="number" id="estimated-time" name="estimated_duration" value="{{ form.estimated_duration.value|default:'30' }}">
                            </div>
                        </div>
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="id_impact">Impact</label>
                                {{ form.impact }}
                            </div>
                        </div>
                    </div>
                    <div class="input-group">
                        <label for="id_tags">Tags</label>
                        {{ form.tags }}
                    </div>
                    <div class="select-group">
                        <label for="target-muscles">Target Muscles</label>
                        {{ form.target_muscles }}
                    </div>
                    <div class="select-group">
                        <label for="id_equipment">Equipment</label>
                        {{ form.equipment }}
                    </div>
                    <input id="exercise-routine" type="hidden" name="routine" value="{{ form.routine.value|default:'' }}">
                    <div class="input-group">
                        {% if form.routine_name.value %}
                        <input type="submit" value="Update Routine">
                        {% else %}
                        <input type="submit" value="Create Routine">
                        {% endif %}
                    </div>
                </form>
            </div>
            <div class="col-50 col-md-100 form-container">
                <h3>Create Routine</h3>
                <div id="cardio-routine-creator">
                    <h5>Cardio</h5>
                    <div class="row">
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="cardio-exercise">Exercise</label>
                                <input type="text" name="cardio_exercise" id="cardio-exercise">
                            </div>
                        </div>
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="cardio-duration">Time</label>
                                <input type="number" name="cardio_duration" id="cardio-duration" value="30" min="0">
                            </div>
                        </div>
                    </div>

                    <div class="input-group">
                        <button id="add-cardio-exercise" class="btn btn-primary">Add</button>
                    </div>
                </div>
                <div id="strength-routine-creator" style="display: none">
                    <h5>Strength</h5>
                    <div class="input-group">
                        <label for="strength-exercise">Exercise</label>
                        <input type="text" name="strength_exercise" id="strength-exercise">
                    </div>
                    <div class="row">
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="num-reps">Reps</label>
                                <input type="number" name="reps" id="num-reps" value="10" min="0">
                            </div>
                        </div>
                        <div class="col-50 col-md-100">
                            <div class="input-group">
                                <label for="num-sets">Sets</label>
                                <input type="number" name="sets" id="num-sets" value="3" min="0">
                            </div>
                        </div>
                    </div>
                    <div class="input-group">
                        <button id="add-strength-exercise" class="btn btn-primary">Add</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
                <div class="col-100 col-md-100 form-container">
                    <h3>Routine</h3>
                    <table id="routine-table">
                        <thead>
                            <tr>
                                <th scope="col">Exercise</th>
                                <th scope="col" class="for-strength-routine">Reps</th>
                                <th scope="col" class="for-strength-routine">Sets</th>
                                <th scope="col" class="for-cardio-routine">Time(seconds)</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>

                    <div id="mobile-table">
                    </div>
                </div>
            </div>
        {% block routine_extra %}
        {% endblock %}
    </div>
</div>
{% endblock %}

src/project/application/templates/application/login.html
{% extends "application/base.html" %}
{% load static %}

{% block content %}
<div class="center-content">
    <div id="login-form" class="login-form-container">
        <div class="centered-image">
            <img src="{% static 'application/images/ForgeFitness.webp' %}" alt="Forge Fitness Logo">
        </div>
        <form action="." method="post">
            {% csrf_token %}
            <div class="input-group">
                <label for="username">Username</label>
                <input type="text" name="username" id="username" required>
            </div>
            <div class="input-group">
                <label for="password">Password</label>
                <input type="password" name="password" id="password" required>
            </div>
            <div class="input-group">
                <input type="submit" value="Login">
            </div>
        </form>
        <div class="input-group" style="display: flex">
            <div class="w50">
                <button class="btn btn-danger">Forgot Password?</button>
            </div>
            <div class="w50">
                <a href="/create-account">
                    <button class="btn btn-secondary">Create Account</button>
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/project/application/templates/application/menu_bar.html
{% load static %}

<script src="{% static 'application/js/menu_bar.js' %}"></script>
<link rel="stylesheet" href="{% static 'application/css/menu_bar.css' %}">
<div id="left-menu">
    <div id="menu-bar" style="left: -500px;">
        <div>
            <i id="toggle-menu-close" class="fa-solid fa-x" style="display: none"></i>
        </div>
        <div class="logo-container">
            <img src="{% static 'application/images/ForgeFitness.webp' %}" alt="Application Logo">
        </div>
        <div id="links">
            <ul>
                <li class="group-link">
                    Exercise Routines
                    <ul>
                        <li class="link"><a href="{% url 'create_routine' %}">Create</a></li>
                        <li class="link"><a href="{% url 'my_routines' %}">My Routines</a></li>
                        <li class="link"><a href="">Search for Routines</a></li>
                    </ul>
                </li>
                <li class="group-link">
                    Progress
                    <ul>
                        <li class="link"><a href="">Goals</a></li>
                        <li class="link"><a href="">History</a></li>
                    </ul>
                </li>
                <li class="link"><a href="">Settings/Account</a></li>
                {% if user.is_staff or user.is_superuser %}
                    <li class="link"><a href="/admin">Admin</a></li>
                {% endif %}
                <li class="logout-btn"><a class="logout-btn" href="{% url 'logout'%}">Logout</a></li>
            </ul>
        </div>
    </div>
    <div>
        <i id="toggle-menu-open" class="fa-solid fa-bars"></i>
    </div>
</div>